#!/bin/bash
EXTRA_ARGS=$@

### The following assumes you are building in a subdirectory of ACCESS Root
ACCESS=$(cd ..; pwd)

TPL=${ACCESS}
MPI=OFF

### Change this to point to the compilers you want to use
CC=gcc

### Change this to point to the compilers you want to use
if [ "$MPI" == "ON" ]
then
  CC=mpicc
else
  CC=gcc
# CC=clang
fi

rm -f CMakeCache.txt

cmake  \
-D SEACASProj_ENABLE_SEACASExodus=ON \
-D SEACASProj_ENABLE_TESTS=ON \
-D CMAKE_INSTALL_PREFIX:PATH=${ACCESS} \
-D BUILD_SHARED_LIBS:BOOL=ON \
-D CMAKE_C_COMPILER:FILEPATH=${CC} \
-D TPL_ENABLE_Netcdf:BOOL=ON \
-D TPL_ENABLE_MPI=${MPI} \
\
-D NetCDF_ROOT:PATH=${TPL} \
-D HDF5_ROOT:PATH=${TPL} \
-D HDF5_NO_SYSTEM_PATHS=ON \
\
-D SEACASProj_SKIP_FORTRANCINTERFACE_VERIFY_TEST:BOOL=ON \
$EXTRA_ARGS \
../



