SET(SEACAS_VERSION 15)
SET(SEACAS_MAJOR_VERSION 10)
SET(SEACAS_MAJOR_MINOR_VERSION 1510)
SET(SEACAS_VERSION_STRING "15.10 (Dev)")
SET(SEACAS_ENABLE_DEVELOPMENT_MODE_DEFAULT ON) # Change to 'OFF' for a release
