SET(SEACASProj_VERSION 2.0)
SET(SEACASProj_MAJOR_VERSION 2)
SET(SEACASProj_MAJOR_MINOR_VERSION 020000)
SET(SEACASProj_VERSION_STRING "2.0 (Dev)")
SET(SEACASProj_ENABLE_DEVELOPMENT_MODE_DEFAULT ON) # Change to 'OFF' for a release
