SET(Seacas_VERSION 2.0)
SET(Seacas_MAJOR_VERSION 2)
SET(Seacas_MAJOR_MINOR_VERSION 020000)
SET(Seacas_VERSION_STRING "2.0 (Dev)")
SET(Seacas_ENABLE_DEVELOPMENT_MODE_DEFAULT ON) # Change to 'OFF' for a release
