#! /bin/sh
rm -f config.cache
LIBRARYSUBDIR=lib; export LIBRARYSUBDIR
CC='pgcc  -tp=k8-64 -fast'; export CC
CFLAGS='-I../libsrc -Mframe  -O      -I/scratch/gdsjaar/SEACAS-SF/inc  -DBuild64 -Dlinux -DADDC_     -I./  -I/scratch/gdsjaar/SEACAS-SF/inc -fpic'; export CFLAGS
CXX='pgCC  -tp=k8-64 -fast'; export CXX
CXXFLAGS='-I../libsrc -Mframe -O     -I/scratch/gdsjaar/SEACAS-SF/inc -DBuild64 -Dlinux -DADDC_     -I./  -I/scratch/gdsjaar/SEACAS-SF/inc -fpic'; export CXXFLAGS
CPPFLAGS='-DNDEBUG'; export CPPFLAGS
AR_FLAGS='cru'; export AR_FLAGS
LDFLAGS='    '; export LDFLAGS

./configure --prefix /scratch/gdsjaar/SEACAS-SF $1
