if (${EXODUS_THREADSAFE})
TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_TPLS Netcdf
  LIB_OPTIONAL_TPLS Pthread HDF5 MPI
  TEST_REQUIRED_TPLS Netcdf
)
else()
TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_TPLS Netcdf Pthread
  LIB_OPTIONAL_TPLS HDF5 MPI
  TEST_REQUIRED_TPLS Netcdf
)
endif()
