/*****************************************************************************
 * CVS File Information :
 *    $RCSfile: kdd_mpi_config.h,v $
 *    $Author: gdsjaar $
 *    $Date: 2009/06/09 18:50:40 $
 *    $Revision: 1.1 $
 ****************************************************************************/
/* mpi_config.h generated by Karen Devine  1 March 2005 */
/* For now, just manually define the values.  We may do 
 * something more intelligent later (particularly wrt fortran mangling)
 * based on Mitchell's F90 interface for Zoltan.
 *
 * Only values that appear to actually be used in the code are defined here.
 */

/* C equivalent of FORTRAN DOUBLE PRECISION */
#define MPI_FORTRAN_DOUBLE double

/* C equivalent of FORTRAN INTEGER */
#define MPI_FORTRAN_INTEGER int

/* Mangling template */
#define MPI_FORTRAN_MANGLING_PATTERNS "_"

/* Version number of package */
#define VERSION 0.1a6
