##############################################################################
# Zoltan Library for Parallel Applications                                   #
# Copyright (c) 2000,2001,2002, Sandia National Laboratories.                #
# This software is distributed under the GNU Lesser General Public License.  #
# For more info, see the README file in the top-level Zoltan directory.      # 
##############################################################################
##############################################################################
# CVS File Information
#    $RCSfile: CVS-HEADER.MAKE,v $
#    $Author: gdsjaar $
#    $Date: 2009/06/09 18:37:55 $
#    $Revision: 1.1 $
##############################################################################

