$ FORT ABAFIG
$ DEV = P1
$ IF DEV .EQS. "" THEN DEV = "LS5"
$ PLTDEV = "SNL$UCODES:PLT/L,SYS$VDI:VDI''DEV'/L,VDISEC/L,CDRLIB/L/I=CDRABC"
$ LINK ABAFIG, 'PLTDEV'
$ DELETE ABAFIG.OBJ;*
$ RUN ABAFIG
$ DELETE ABAFIG.EXE;*
