# NOTE: This action requires write permissions to be set in your GitHub
#       repo/fork for it to be able to commit changes.
#
# This is currently enabled via:
#
#   settings > Actions > General > Workflow permissions
#
# which you will need to set to "Read and write permissions"
#

name: Clang Format Commit Changes

on: 
  workflow_dispatch:
  push:

concurrency:  
  group: ${{ github.workflow}}-${{ github.head_ref }}  
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  formatting-check:
    name: Commit clang-format changes
    runs-on: ubuntu-latest

    permissions:
        contents: write # In order to allow EndBug/add-and-commit to commit changes
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Fix C++ and C formatting issues detected by clang-format
      uses: DoozyX/clang-format-lint-action@v0.20
      with:
        source: 'packages/seacas'
        exclude: 'packages/seacas/doc-source'
        extensions: 'c,C,cc,h,cpp,hpp'
        clangFormatVersion: 18
        inplace: True
        style: file

    - uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10.0.0
      with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'Committing clang-format changes'
