name: SEACAS MSYS2 Build
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

concurrency:  
  group: ${{ github.workflow}}-${{ github.head_ref }}  
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: msys2/setup-msys2@66cd2cce69caa17b53920067426061ca1de3a884 # v2.32.0
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain make mingw-w64-x86_64-hdf5 mingw-w64-x86_64-cgns mingw-w64-x86_64-netcdf mingw-w64-x86_64-zlib mingw-w64-x86_64-gcc-fortran mingw-w64-x86_64-gcc-libgfortran mingw-w64-x86_64-cmake mingw-w64-x86_64-fmt mingw-w64-x86_64-catch
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          ./ci-msys2-build.sh
